---
- hosts: raspberry
  become: yes
  tasks:
  - name: Install packages for Wireguard
    package:
      name: 
        - wireguard
        - wireguard-dkms
        - wireguard-tools
        - dkms 
        - raspberrypi-kernel-headers
      state: present

  - name: Create /etc/wireguard directory
    file:
      path: /etc/wireguard
      state: directory
      mode: 0600

  - name: Check if server_private.key exists
    stat:
      path: /etc/wireguard/server_private.key
    register: stat_server_private_key_file

  - name: Create private server key
    shell: |
      wg genkey > server_private.key
    args:
      chdir: /etc/wireguard
    when: not stat_server_private_key_file.stat.exists

  - name: Get private server key value
    slurp:
      src: /etc/wireguard/server_private.key
    register: server_private_key

  - name: Check if server_public.key exists
    stat:
      path: /etc/wireguard/server_public.key
    register: stat_server_public_key_file

  - name: Create public server key
    shell: |
      wg pubkey > server_public.key < server_private.key
    args:
      chdir: /etc/wireguard
    when: not stat_server_public_key_file.stat.exists

  - name: Get public server key value
    slurp:
      src: /etc/wireguard/server_public.key
    register: server_public_key

  - name: Create clients
    include_tasks: create_clients.yml
    with_items: "{{ clients }}"

  - name: Template wg0.conf file
    template:
      src: wg0.conf.j2
      dest: /etc/wireguard/wg0.conf
    notify: Restart wireguard interface

  - name: Template clients files
    include_tasks: create_clients_conf.yml
    with_items: "{{ clients }}"

  - name: Add parameter in sysctl.conf for ip forward
    lineinfile:
      path: /etc/sysctl.conf
      line: net.ipv4.ip_forward=1

  - name: Reload kernel parameters
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: yes
      reload: yes

  - name: Enable wg-quick@wg0
    systemd:
      enabled: yes
      name: wg-quick@wg0

  handlers:
  - name: Restart wireguard interface
    shell: |
      wg-quick down wg0
      wg-quick up wg0
...